export const maxUserDataValues = Object.freeze({
  MAX_LENGTH_FIRSTNAME: 90,
  MAX_LENGTH_LASTNAME: 90,
  MAX_LENGTH_USERNAME: 30,
  MAX_LENGTH_PASSWORD: 30,
  MAX_LENGTH_ADDRESS: 110,
  MAX_LENGTH_GENDER: 30,
  MAX_LENGTH_WEBSITE: 110,
  MAX_LENGTH_PHONE: 15,
  MAX_LENGTH_STORY: 200
})

export const minUserDataValues = Object.freeze({
  MIN_LENGTH_FIRSTNAME: 2,
  MIN_LENGTH_LASTNAME: 2,
  MIN_LENGTH_USERNAME: 5,
  MIN_LENGTH_PASSWORD: 8,
  MIN_LENGTH_ADDRESS: 0,
  MIN_LENGTH_GENDER: 0,
  MIN_LENGTH_WEBSITE: 0,
  MIN_LENGTH_PHONE: 5,
  MIN_LENGTH_STORY: 0
})
